name: Time
main: com.tengel.time.Time
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: 0.1
description: Provides additional events to the server
authors: [Engeltj]
commands:
  ghost:
    description: Makes you invisible to another player
  life:
    description: Checks how much life you have left remaining